enum TipoAccionEnum {

    SELECCIONAR ="SELECCIONAR",
    NUEVO = "NUEVO",
    ACTUALIZAR = "ACTUALIZAR",
    ELIMINAR = "ELIMINAR",
    GUARDAR_CAMBIOS = "GUARDAR_CAMBIOS",

    BUSCAR_TODOS = "BUSCAR_TODOS",
    BUSCAR = "BUSCAR"
}

export {TipoAccionEnum};